# Generated by Django 4.0.3 on 2022-04-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('frc_key', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
