# Generated by Django 4.0.3 on 2022-04-02 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_points', models.IntegerField(default=0)),
                ('drive_type', models.CharField(max_length=45)),
                ('target', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'High'), (3, 'Both'), (0, 'None')])),
                ('climb', models.PositiveSmallIntegerField(choices=[(4, 'Low Bar'), (6, 'Middle Bar'), (10, 'High Bar'), (0, 'No Climb')])),
                ('frc_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robot', to='scout.team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='pit_scout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scout.robot'),
        ),
    ]
