# Generated by Django 4.0.3 on 2022-04-02 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0002_robot_team_pit_scout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='climb',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Low Bar'), (6, 'Middle Bar'), (10, 'High Bar'), (15, 'Traversal Bar'), (0, 'No Climb')]),
        ),
        migrations.AlterField(
            model_name='robot',
            name='frc_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='scout.team'),
        ),
    ]
