# Generated by Django 4.0.3 on 2022-04-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0003_alter_robot_climb_alter_robot_frc_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_taxi', models.BooleanField(default=False)),
                ('auto_ball', models.IntegerField(default=0, max_length=1)),
                ('auto_target', models.SmallIntegerField(choices=[(4, 'High Goal'), (2, 'Low Goal'), (0, 'No Auto')], default=0)),
                ('tele_target', models.SmallIntegerField(choices=[(2, 'High Goal'), (1, 'Low Goal'), (0, 'No Teleop Shooting')], default=1)),
                ('tele_cargo', models.IntegerField(default=0, max_length=2)),
                ('tele_distance', models.SmallIntegerField(choices=[(1, 'Inside Tarmac Only'), (2, 'Outside Tarmac Only'), (3, 'Anywhere'), (0, 'N/A')], default=0)),
                ('climb_height', models.SmallIntegerField(choices=[(4, 'Low Bar'), (6, 'Mid Bar'), (10, 'High Bar'), (15, 'Traversal Bar'), (0, 'No Climb')], default=0)),
                ('climb_time', models.IntegerField(default=0, max_length=2)),
                ('driver_rating', models.SmallIntegerField(choices=[(1, 'Really Bad'), (2, 'Bad'), (3, 'Moderate'), (4, 'Good'), (5, 'Really Good')], default=1)),
                ('comments', models.CharField(max_length=250)),
            ],
        ),
    ]
