# Generated by Django 4.0.3 on 2022-04-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0004_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='tele_target',
            field=models.SmallIntegerField(choices=[(2, 'High Goal'), (1, 'Low Goal'), (0, 'No Teleop Shooting')], default=0),
        ),
    ]
