# Generated by Django 4.0.3 on 2022-04-02 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0006_matchresult_delete_match_remove_team_pit_scout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='frc_team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='robot', to='scout.team'),
        ),
    ]
