# Generated by Django 4.0.3 on 2022-04-03 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0007_alter_robot_frc_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='frc_team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='robot', to='scout.team'),
        ),
    ]
