# Generated by Django 4.0.3 on 2022-04-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0008_alter_robot_frc_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='auto_target',
            field=models.SmallIntegerField(choices=[('High Goal', 'High Goal'), ('Low Goal', 'Low Goal'), ('None', 'No Auto')], default='None'),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='climb_height',
            field=models.SmallIntegerField(choices=[('Low Bar', 'Low Bar'), ('Mid Bar', 'Mid Bar'), ('High Bar', 'High Bar'), ('Traversal Bar', 'Traversal Bar'), ('None', 'No Climb')], default='None'),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='driver_rating',
            field=models.SmallIntegerField(choices=[('Really Bad', 'Really Bad'), ('Bad', 'Bad'), ('Moderate', 'Moderate'), ('Good', 'Good'), ('Really Good', 'Really Good')], default='Really Bad'),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='tele_distance',
            field=models.SmallIntegerField(choices=[('Close', 'Inside Tarmac Only'), ('Far', 'Outside Tarmac Only'), ('Anywhere', 'Anywhere'), ('None', 'N/A')], default='None'),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='tele_target',
            field=models.SmallIntegerField(choices=[('High Goal', 'High Goal'), ('Low Goal', 'Low Goal'), ('None', 'No Teleop Shooting')], default='None'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='climb',
            field=models.PositiveSmallIntegerField(choices=[('Low Bar', 'Low Bar'), ('Mid Bar', 'Middle Bar'), ('High Bar', 'High Bar'), ('Traversal Bar', 'Traversal Bar'), ('None', 'No Climb')]),
        ),
        migrations.AlterField(
            model_name='robot',
            name='target',
            field=models.PositiveSmallIntegerField(choices=[('Low Goal', 'Low'), ('High Goal', 'High'), ('Both Goals', 'Both'), ('None', 'None')]),
        ),
    ]
