# Generated by Django 4.0.3 on 2022-04-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0009_alter_matchresult_auto_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='climb',
            field=models.CharField(choices=[('Low Bar', 'Low Bar'), ('Mid Bar', 'Middle Bar'), ('High Bar', 'High Bar'), ('Traversal Bar', 'Traversal Bar'), ('None', 'No Climb')], max_length=13),
        ),
        migrations.AlterField(
            model_name='robot',
            name='target',
            field=models.CharField(choices=[('Low Goal', 'Low'), ('High Goal', 'High'), ('Both Goals', 'Both'), ('None', 'None')], max_length=11),
        ),
    ]
