# Generated by Django 4.0.3 on 2022-04-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0010_alter_robot_climb_alter_robot_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='comments',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
