# Generated by Django 4.0.3 on 2022-04-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0011_alter_matchresult_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='auto_target',
            field=models.CharField(choices=[('High Goal', 'High Goal'), ('Low Goal', 'Low Goal'), ('None', 'No Auto')], default='None', max_length=13),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='climb_height',
            field=models.CharField(choices=[('Low Bar', 'Low Bar'), ('Mid Bar', 'Mid Bar'), ('High Bar', 'High Bar'), ('Traversal Bar', 'Traversal Bar'), ('None', 'No Climb')], default='None', max_length=13),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='comments',
            field=models.CharField(default='No comments', max_length=250),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='driver_rating',
            field=models.CharField(choices=[('Really Bad', 'Really Bad'), ('Bad', 'Bad'), ('Moderate', 'Moderate'), ('Good', 'Good'), ('Really Good', 'Really Good')], default='Really Bad', max_length=13),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='tele_distance',
            field=models.CharField(choices=[('Close', 'Inside Tarmac Only'), ('Far', 'Outside Tarmac Only'), ('Anywhere', 'Anywhere'), ('None', 'N/A')], default='None', max_length=13),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='tele_target',
            field=models.CharField(choices=[('High Goal', 'High Goal'), ('Low Goal', 'Low Goal'), ('None', 'No Teleop Shooting')], default='None', max_length=13),
        ),
    ]
