# Generated by Django 4.0.3 on 2022-04-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0012_alter_matchresult_auto_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='match_number',
            field=models.IntegerField(default=0),
        ),
    ]
