# Generated by Django 4.0.3 on 2022-04-03 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0013_matchresult_match_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='frc_team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='robot', to='scout.team', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='robot_report',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='scout.robot', verbose_name='Robot'),
        ),
    ]
