# Generated by Django 4.0.3 on 2022-04-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0014_alter_robot_frc_team_alter_team_robot_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchresult',
            old_name='auto_ball',
            new_name='auto_scored',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='tele_cargo',
            new_name='tele_scored',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='climb_time',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='tele_distance',
        ),
        migrations.AddField(
            model_name='matchresult',
            name='climb_attempted',
            field=models.BooleanField(default=False),
        ),
    ]
