# Generated by Django 4.0.3 on 2022-04-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0017_remove_matchresult_climb_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='climb_points',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Low Bar'), (6, 'Mid Bar'), (10, 'High Bar'), (15, 'Traversal Bar'), (0, 'Failed')], default=0),
        ),
    ]
